name: Customer Due Tracker Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  customer-due-tracker-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest || echo "No tests found, skipping"

      - name: Deployment
        run: |
          echo "Started the Deployment"
          echo "Deployment In Progress"
          echo "Deployment Completed"
